### PR TITLE
support editing of cover image [QC-141]

### PR DESCRIPTION
**Pull request by dan13ram**

### CODE REVIEW

**Comment by vidvidvid** [comment]
@dan13ram could you please check & fix the conflicts?

**Comment by vidvidvid** [comment]
https://deploy-preview-136--quest-chains-dev.netlify.app/chain/0x13881/0xe53f39b8d898dda3366efafd6f3aa218fdc2f2fe

i edited the chain and uploaded a cover image, but it doesn't seem to appear anywhere. it should be displayed in the background, right? also when i wanted to edit it again there was no clear indication that an image has been previously uploaded.
this might be a UX thing which needs fixing or there might be some erroneous behaviour going on, could you pls look into it?

**Comment by dan13ram** [comment]
> https://deploy-preview-136--quest-chains-dev.netlify.app/chain/0x13881/0xe53f39b8d898dda3366efafd6f3aa218fdc2f2fe
> 
> i edited the chain and uploaded a cover image, but it doesn't seem to appear anywhere. it should be displayed in the background, right? also when i wanted to edit it again there was no clear indication that an image has been previously uploaded. this might be a UX thing which needs fixing or there might be some erroneous behaviour going on, could you pls look into it?

I have a feeling it was an issue with our default ipfs gateway not working. I've fixed that along with a bunch of other minor fixes. Can you check again now ?

**Comment by vidvidvid** [comment]
@dan13ram works now! :)

**Review by vidvidvid — APPROVED** [review]

**Pull request merged**
