### PR TITLE
Add `react-medium-image-zoom` to zoom submission images [QC-174]

### PR DESCRIPTION
**Pull request by parv3213**
Prototype to fix https://github.com/quest-chains/dapp/issues/141.

Before clicking on the image: 
Screenshot 2023-02-10 at 3 04 56 PM

After clicking on the image: 
Screenshot 2023-02-10 at 3 09 25 PM

If everyone is okay with this approach, then we can replicate this at other places. The minified (gzipped) import cost is 4.4k.

### CODE REVIEW

**Review by vidvidvid — APPROVED** [review]
nice and simple solution!

**Comment by vidvidvid** [comment]
what are the other places you wanted to replicate this at? btw is there a way to keep the background of the app instead of having the white background?

**Comment by parv3213** [comment]
> nice and simple solution!

Awesome. I will replicate this at other required places.

**Comment by parv3213** [comment]
> what are the other places you wanted to replicate this at? btw is there a way to keep the background of the app instead of having the white background?

I think we should get an option to zoom where ever there is an uploaded image. 
Yeah, I think we can the app background. I will try.

**Comment by parv3213** [comment]
@vidvidvid ready PR is ready for review.

**Review by vidvidvid — COMMENTED** [review]
the interaction is smooth, but something makes the right scrollbar disappear when the image is zoomed in, which causes the twitching of the menu elements. could you look into it? it's not a major issue, so if it is too troublesome, we can skip it. in that case just please open an issue for it.
https://user-images.githubusercontent.com/35112939/218091227-a3854919-5372-44e6-b505-b84b3f007fb2.mov

**Comment by dan13ram** [comment]
Looks good. But do we an extra dependency for this? I feel we could implement it ourselves but perhaps not worth the effort?

**Comment by parv3213** [comment]
> the interaction is smooth, but something makes the right scrollbar disappear when the image is zoomed in, which causes the twitching of the menu elements. could you look into it? it's not a major issue, so if it is too troublesome, we can skip it. in that case just please open an issue for it.
> 
>  Screen.Recording.2023-02-10.at.13.20.29.mov

This actually happens with current Modals as well. https://www.loom.com/share/e0427fd10acb4856bb48f5cdb16663c3.
I believe it is due to the styled scrollbar that we have added.

**Comment by vidvidvid** [comment]
@dan13ram it's a small dependency and it's rly convenient, i see no harm in using it

**Comment by vidvidvid** [comment]
@parv3213 kk, i'll open an issue to fix this in all of the cases

**Comment by parv3213** [comment]
> @parv3213 kk, i'll open an issue to fix this in all of the cases #172

Do you have any ideas on how we can fix it? Maybe setting the modal width = 100vw - the scrollbar width?

**Pull request merged**
